# Generated by Django 5.2.7 on 2025-11-03 04:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "장소 성격 LLM",
                "verbose_name_plural": "장소 성격 LLM",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그",
            },
        ),
        migrations.CreateModel(
            name="Travel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("author_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "다이어리 목록",
                "verbose_name_plural": "다이어리 목록",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="travel.chatmessage",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("participants", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="travel.chatroom"
            ),
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "place_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        null=True,
                        unique=True,
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviewCnt", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("city_gu", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("lat", models.CharField(blank=True, max_length=50, null=True)),
                ("lon", models.CharField(blank=True, max_length=50, null=True)),
                ("image_urls", models.TextField(blank=True, null=True)),
                ("opening_hours", models.TextField(blank=True, null=True)),
                ("regdate", models.DateTimeField(auto_now_add=True)),
                ("chgdate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
                "indexes": [
                    models.Index(
                        fields=["category", "city", "city_gu"],
                        name="travel_plac_categor_ea1364_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UploadEntry",
            fields=[],
            options={
                "verbose_name": "데이터 업로드",
                "verbose_name_plural": "데이터 업로드",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("travel.place",),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("place_id", models.CharField(db_index=True, max_length=120)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("like", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "place_id", "author", "content"),
                        name="uniq_review_placeid_author_content",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_file",
                    models.FileField(null=True, upload_to="diary_media/%Y/%m/%d/"),
                ),
                ("media_type", models.CharField(blank=True, max_length=10)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("author_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="diary_entries", to="travel.tag"
                    ),
                ),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entries",
                        to="travel.travel",
                    ),
                ),
            ],
            options={
                "verbose_name": "다이어리 상세",
                "verbose_name_plural": "다이어리 상세",
            },
        ),
        migrations.CreateModel(
            name="TravelPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("user_query", models.JSONField(blank=True, null=True)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chatroom",
            name="travel_plan1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatrooms_as_plan1",
                to="travel.travelplan",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="travel_plan2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatrooms_as_plan2",
                to="travel.travelplan",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nickname", models.CharField(max_length=30)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("age_range", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("languages", models.CharField(blank=True, max_length=100)),
                ("travel_style", models.CharField(blank=True, max_length=50)),
                ("budget", models.CharField(blank=True, max_length=50)),
                ("smoking", models.CharField(blank=True, max_length=20)),
                ("drinking", models.CharField(blank=True, max_length=20)),
                ("sns", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("mbti", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("place_code", models.CharField(db_index=True, max_length=50)),
                ("place_title", models.CharField(max_length=200)),
                ("season_spring", models.IntegerField(blank=True, null=True)),
                ("season_summer", models.IntegerField(blank=True, null=True)),
                ("season_autumn", models.IntegerField(blank=True, null=True)),
                ("season_winter", models.IntegerField(blank=True, null=True)),
                ("mbti_E", models.IntegerField(blank=True, null=True)),
                ("mbti_I", models.IntegerField(blank=True, null=True)),
                ("mbti_S", models.IntegerField(blank=True, null=True)),
                ("mbti_N", models.IntegerField(blank=True, null=True)),
                ("mbti_T", models.IntegerField(blank=True, null=True)),
                ("mbti_F", models.IntegerField(blank=True, null=True)),
                ("mbti_J", models.IntegerField(blank=True, null=True)),
                ("mbti_P", models.IntegerField(blank=True, null=True)),
                ("group_couple", models.IntegerField(blank=True, null=True)),
                ("group_friends", models.IntegerField(blank=True, null=True)),
                ("group_family", models.IntegerField(blank=True, null=True)),
                ("group_solo", models.IntegerField(blank=True, null=True)),
                ("age_20s", models.IntegerField(blank=True, null=True)),
                ("age_30s", models.IntegerField(blank=True, null=True)),
                ("age_40s", models.IntegerField(blank=True, null=True)),
                ("age_50plus", models.IntegerField(blank=True, null=True)),
                ("gender_female", models.IntegerField(blank=True, null=True)),
                ("gender_male", models.IntegerField(blank=True, null=True)),
                ("keywords_csv", models.TextField(blank=True, default="")),
                ("themes_csv", models.TextField(blank=True, default="")),
                ("raw_json", models.JSONField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="travel.place",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("place",), name="unique_analysis_per_place"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSelectedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chosen_by",
                        to="travel.travelplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "plan", "start_date", "end_date")},
            },
        ),
    ]
