# Generated by Django 5.2.7 on 2025-10-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "데이터 업로드",
                "verbose_name_plural": "데이터 업로드",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "place_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        null=True,
                        unique=True,
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviewCnt", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("city_gu", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("regdate", models.DateTimeField(auto_now_add=True)),
                ("chgdate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
                "indexes": [
                    models.Index(
                        fields=["category", "city", "city_gu"],
                        name="travel_plac_categor_ea1364_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("place_id", models.CharField(db_index=True, max_length=120)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("like", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("place_id", "name", "author", "content"),
                        name="uniq_review_placeid_author_content",
                    )
                ],
            },
        ),
    ]
