# Generated by Django 5.2.7 on 2025-11-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="travel_plan1",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="travel_plan2",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="plan_user_1",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatroom",
            name="plan_user_2",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatroom",
            name="travel_plan1_pk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="travel_plan2_pk",
            field=models.IntegerField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='travel',
        #     name='plan',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to='travel.travelplan'),
        # ),
    ]
