# Generated by Django 5.0.14 on 2025-10-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place_code', models.CharField(max_length=50)),
                ('place_title', models.CharField(max_length=200)),
                ('season_spring', models.IntegerField(blank=True, null=True)),
                ('season_summer', models.IntegerField(blank=True, null=True)),
                ('season_autumn', models.IntegerField(blank=True, null=True)),
                ('season_winter', models.IntegerField(blank=True, null=True)),
                ('mbti_E', models.IntegerField(blank=True, null=True)),
                ('mbti_I', models.IntegerField(blank=True, null=True)),
                ('mbti_S', models.IntegerField(blank=True, null=True)),
                ('mbti_N', models.IntegerField(blank=True, null=True)),
                ('mbti_T', models.IntegerField(blank=True, null=True)),
                ('mbti_F', models.IntegerField(blank=True, null=True)),
                ('mbti_J', models.IntegerField(blank=True, null=True)),
                ('mbti_P', models.IntegerField(blank=True, null=True)),
                ('group_couple', models.IntegerField(blank=True, null=True)),
                ('group_friends', models.IntegerField(blank=True, null=True)),
                ('group_family', models.IntegerField(blank=True, null=True)),
                ('group_solo', models.IntegerField(blank=True, null=True)),
                ('age_20s', models.IntegerField(blank=True, null=True)),
                ('age_30s', models.IntegerField(blank=True, null=True)),
                ('age_40s', models.IntegerField(blank=True, null=True)),
                ('age_50plus', models.IntegerField(blank=True, null=True)),
                ('gender_female', models.IntegerField(blank=True, null=True)),
                ('gender_male', models.IntegerField(blank=True, null=True)),
                ('keywords_csv', models.TextField()),
                ('themes_csv', models.TextField()),
                ('raw_json', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='travel.place')),
            ],
            options={
                'verbose_name': 'Place Analysis',
                'verbose_name_plural': 'Place Analyses',
                'db_table': 'travel_placeanalysis',
            },
        ),
    ]
