# Generated by Django 5.2.7 on 2025-10-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataUpload",
        ),
        migrations.RemoveConstraint(
            model_name="review",
            name="uniq_review_placeid_author_content",
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("name", "place_id", "author", "content"),
                name="uniq_review_placeid_author_content",
            ),
        ),
    ]
