# Generated by Django 5.2.5 on 2025-10-27 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '장소 성격 LLM',
                'verbose_name_plural': '장소 성격 LLM',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='users',
            new_name='participants',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='travel_plan1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_as_plan1', to='travel.travelplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='travel_plan2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_as_plan2', to='travel.travelplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='travel.chatmessage')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_code', models.CharField(db_index=True, max_length=50)),
                ('place_title', models.CharField(max_length=200)),
                ('season_spring', models.IntegerField(blank=True, null=True)),
                ('season_summer', models.IntegerField(blank=True, null=True)),
                ('season_autumn', models.IntegerField(blank=True, null=True)),
                ('season_winter', models.IntegerField(blank=True, null=True)),
                ('mbti_E', models.IntegerField(blank=True, null=True)),
                ('mbti_I', models.IntegerField(blank=True, null=True)),
                ('mbti_S', models.IntegerField(blank=True, null=True)),
                ('mbti_N', models.IntegerField(blank=True, null=True)),
                ('mbti_T', models.IntegerField(blank=True, null=True)),
                ('mbti_F', models.IntegerField(blank=True, null=True)),
                ('mbti_J', models.IntegerField(blank=True, null=True)),
                ('mbti_P', models.IntegerField(blank=True, null=True)),
                ('group_couple', models.IntegerField(blank=True, null=True)),
                ('group_friends', models.IntegerField(blank=True, null=True)),
                ('group_family', models.IntegerField(blank=True, null=True)),
                ('group_solo', models.IntegerField(blank=True, null=True)),
                ('age_20s', models.IntegerField(blank=True, null=True)),
                ('age_30s', models.IntegerField(blank=True, null=True)),
                ('age_40s', models.IntegerField(blank=True, null=True)),
                ('age_50plus', models.IntegerField(blank=True, null=True)),
                ('gender_female', models.IntegerField(blank=True, null=True)),
                ('gender_male', models.IntegerField(blank=True, null=True)),
                ('keywords_csv', models.TextField(blank=True, default='')),
                ('themes_csv', models.TextField(blank=True, default='')),
                ('raw_json', models.JSONField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='travel.place')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('place',), name='unique_analysis_per_place')],
            },
        ),
    ]
