# Generated by Django 5.2.7 on 2025-10-30 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_chatmessage_chatreport_chatroom_chatmessage_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="userselectedplan",
            name="endDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userselectedplan",
            name="startDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
