# Generated by Django 5.2.7 on 2025-11-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travel_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='plan',
        ),
    ]
