# Generated by Django 5.2.7 on 2025-10-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_delete_dataupload_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisTool",
            fields=[],
            options={
                "verbose_name": "장소 LLM 분석 도구",
                "verbose_name_plural": "장소 LLM 분석 도구",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("travel.place",),
        ),
        migrations.CreateModel(
            name="UploadEntry",
            fields=[],
            options={
                "verbose_name": "데이터 업로드",
                "verbose_name_plural": "데이터 업로드",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("travel.place",),
        ),
    ]
