# Generated by Django 5.2.7 on 2025-11-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_remove_chatroom_travel_plan1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="user_matched",
            field=models.BooleanField(default=True),
        ),
        # migrations.RemoveField(
        #     model_name='travel',
        #     name='plan',
        # ),
    ]
