# Generated by Django 5.2.7 on 2025-10-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_userselectedplan_enddate_userselectedplan_startdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userselectedplan",
            name="endDate",
        ),
        migrations.RemoveField(
            model_name="userselectedplan",
            name="startDate",
        ),
    ]
