# Generated by Django 5.2.7 on 2025-10-22 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_analysistool_uploadentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalysisTool",
        ),
        migrations.CreateModel(
            name="AnalysisTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "장소 성격 LLM",
                "verbose_name_plural": "장소 성격 LLM",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlaceAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("place_code", models.CharField(db_index=True, max_length=50)),
                ("place_title", models.CharField(max_length=200)),
                ("season_spring", models.IntegerField(blank=True, null=True)),
                ("season_summer", models.IntegerField(blank=True, null=True)),
                ("season_autumn", models.IntegerField(blank=True, null=True)),
                ("season_winter", models.IntegerField(blank=True, null=True)),
                ("mbti_E", models.IntegerField(blank=True, null=True)),
                ("mbti_I", models.IntegerField(blank=True, null=True)),
                ("mbti_S", models.IntegerField(blank=True, null=True)),
                ("mbti_N", models.IntegerField(blank=True, null=True)),
                ("mbti_T", models.IntegerField(blank=True, null=True)),
                ("mbti_F", models.IntegerField(blank=True, null=True)),
                ("mbti_J", models.IntegerField(blank=True, null=True)),
                ("mbti_P", models.IntegerField(blank=True, null=True)),
                ("group_couple", models.IntegerField(blank=True, null=True)),
                ("group_friends", models.IntegerField(blank=True, null=True)),
                ("group_family", models.IntegerField(blank=True, null=True)),
                ("group_solo", models.IntegerField(blank=True, null=True)),
                ("age_20s", models.IntegerField(blank=True, null=True)),
                ("age_30s", models.IntegerField(blank=True, null=True)),
                ("age_40s", models.IntegerField(blank=True, null=True)),
                ("age_50plus", models.IntegerField(blank=True, null=True)),
                ("gender_female", models.IntegerField(blank=True, null=True)),
                ("gender_male", models.IntegerField(blank=True, null=True)),
                ("keywords_csv", models.TextField(blank=True, default="")),
                ("themes_csv", models.TextField(blank=True, default="")),
                ("raw_json", models.JSONField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="travel.place",
                    ),
                ),
            ],
        ),
    ]
