# Generated by Django 5.2.7 on 2025-11-04 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_travel_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to='travel.travelplan'),
        ),
    ]
