# Generated by Django 5.2.7 on 2025-10-30 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_remove_userselectedplan_enddate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userselectedplan",
            name="endDate",
            field=models.DateField(default=datetime.date(2025, 10, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userselectedplan",
            name="startDate",
            field=models.DateField(default=datetime.date(2025, 10, 30)),
            preserve_default=False,
        ),
    ]
