# Generated by Django 5.2.7 on 2025-10-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_delete_analysistool_analysistool_placeanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeanalysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="placeanalysis",
            constraint=models.UniqueConstraint(
                fields=("place",), name="unique_analysis_per_place"
            ),
        ),
    ]
