# Generated by Django 5.2.7 on 2025-11-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_travel_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
