# Generated by Django 5.2.7 on 2025-10-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0005_placeanalysis_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="lat",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="lon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
