# Generated by Django 5.2.7 on 2025-10-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0006_place_lat_place_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="image_urls",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="opening_hours",
            field=models.TextField(blank=True, null=True),
        ),
    ]
