# Generated by Django 5.2.7 on 2025-10-31 05:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0006_travelplan_owner_travelplan_user_query"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="userselectedplan",
            old_name="endDate",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="userselectedplan",
            old_name="startDate",
            new_name="start_date",
        ),
        migrations.AlterUniqueTogether(
            name="userselectedplan",
            unique_together={("user", "plan", "start_date", "end_date")},
        ),
    ]
