# Generated by Django 5.2.7 on 2025-10-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_placeanalysis'),
        ('travel', '0007_place_image_urls_place_opening_hours'),
    ]

    operations = [
    ]
