# Generated by Django 5.2.5 on 2025-10-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_place_image_urls_place_lat_place_lon_and_more'),
        ('travel', '0007_place_image_urls_place_opening_hours'),
    ]

    operations = [
    ]
