# Generated by Django 5.2.7 on 2025-10-29 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_merge_20251029_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'verbose_name': '다이어리 상세', 'verbose_name_plural': '다이어리 상세'},
        ),
        migrations.AlterModelOptions(
            name='placeanalysis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': '다이어리 목록', 'verbose_name_plural': '다이어리 목록'},
        ),
        migrations.RenameField(
            model_name='diaryentry',
            old_name='travel',
            new_name='diary',
        ),
        migrations.AlterField(
            model_name='placeanalysis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='placeanalysis',
            name='keywords_csv',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='placeanalysis',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='travel.place'),
        ),
        migrations.AlterField(
            model_name='placeanalysis',
            name='place_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='placeanalysis',
            name='raw_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='placeanalysis',
            name='themes_csv',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='placeanalysis',
            constraint=models.UniqueConstraint(fields=('place',), name='unique_analysis_per_place'),
        ),
        migrations.AlterModelTable(
            name='placeanalysis',
            table=None,
        ),
    ]
