# Generated by Django 5.2.7 on 2025-10-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_placeanalysis"),
        ("travel", "0009_travelplan_userselectedplan"),
    ]

    operations = []
