# Generated by Django 5.2.7 on 2025-10-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_diaryentry_options_alter_placeanalysis_options_and_more'),
        ('travel', '0010_merge_20251029_1143'),
    ]

    operations = [
    ]
