# Generated by Django 5.2.7 on 2025-10-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_merge_20251029_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mbti',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
