# Generated by Django 5.2.6 on 2025-10-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_remove_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='drinker',
            new_name='drinking',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='smoker',
            new_name='smoking',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_level',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age_range',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sns_link',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='travel_style',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
