# Generated by Django 5.2.6 on 2025-10-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_rename_drinker_userprofile_drinking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='drinking',
            field=models.CharField(blank=True, choices=[('즐김', '즐김'), ('가끔', '가끔'), ('안 마심', '안 마심')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoking',
            field=models.CharField(blank=True, choices=[('흡연', '흡연'), ('비흡연', '비흡연')], max_length=10),
        ),
    ]
