# Generated by Django 5.2.6 on 2025-10-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_userprofile_drinking_alter_userprofile_smoking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sns_link',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sns',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='drinking',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoking',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
