# Generated by Django 5.2.6 on 2025-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_rename_uuid_userprofile_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_range',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
