# Generated by Django 5.2.6 on 2025-10-29 07:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_alter_userprofile_age_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sns',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sns_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='drinking',
            field=models.CharField(blank=True, choices=[('즐김', '즐김'), ('가끔', '가끔'), ('안 마심', '안 마심')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoking',
            field=models.CharField(blank=True, choices=[('흡연', '흡연'), ('비흡연', '비흡연')], max_length=10),
        ),
    ]
