# Generated by Django 5.2.6 on 2025-10-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_remove_userprofile_languages_remove_userprofile_sns_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uuid',
            new_name='unique_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sns_link',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sns',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='drinking',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoking',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
