# Generated by Django 5.2.6 on 2025-10-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_rename_uuid_userprofile_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mbti',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
