"""
Django settings for travelAgent project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()  # .env 파일에서 환경 변수 로드

# 2. 지원할 언어 정의 (언어 코드와 이름)
LANGUAGES = [
    ('ko', 'Korean'),  # 한국어
    ('en', 'English'), # 영어
    ('es', 'Spanish'), # 스페인어
]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise Exception('SECRET_KEY 환경변수가 설정되어 있지 않습니다. .env 파일을 확인하세요.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    "travel.apps.TravelConfig",
    'channels',       # 채널스 등록
    # "ai_planner",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "travelAgent.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

WSGI_APPLICATION = 'travelAgent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    "diary_db": {  # New database for diary app
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "diary_db.sqlite3",
    },
    "chat_db": {  # New database for chat app
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "chat_db.sqlite3",
    }
}

DATABASE_ROUTERS = ['travelAgent.db_routers.DiaryRouter'
                    , 'travelAgent.db_routers.ChatRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko"
TIME_ZONE = "Asia/Seoul"

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles" 
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DATA_DIR = BASE_DIR / "data"

# ASGI 및 Channel Layer 설정
ASGI_APPLICATION = 'travelAgent.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        # 개발 환경용 인메모리 레이어 (DB에만 메시지 저장, 재시작 시 실시간 그룹 정보만 초기화됨)
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

MAPBOX_ACCESS_TOKEN = os.getenv("MAPBOX_ACCESS_TOKEN", "")


# === 로그인 / 로그아웃 경로 설정 ===
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # 1800초 = 30분
SESSION_SAVE_EVERY_REQUEST = True

# ASGI 및 Channel Layer 설정
ASGI_APPLICATION = 'travelAgent.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        # 개발 환경용 인메모리 레이어 (DB에만 메시지 저장, 재시작 시 실시간 그룹 정보만 초기화됨)
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# 로그인 성공 후 리디렉션 URL (로그인 기능 사용 시)
LOGIN_REDIRECT_URL = '/'  # 메인 화면 URL
LOGOUT_REDIRECT_URL = '/accounts/login/' # 로그인 필요 시 이동할 URL

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

