# Generated by Django 5.0.14 on 2025-10-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI API Key')),
                ('google_gemini_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Gemini API Key')),
                ('default_api_model', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT')], default='gemini', max_length=10, verbose_name='기본 AI 모델')),
            ],
            options={
                'verbose_name': 'AI 설정',
                'verbose_name_plural': 'AI 설정',
            },
        ),
    ]
