# Generated by Django 5.0.14 on 2025-10-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisettings',
            name='google_gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='aisettings',
            name='openai_api_key',
        ),
    ]
